# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: 
        steps:
        - task: DotNetCoreInstaller@1
          displayName: install .net 
          inputs:
            packageType: 'sdk'
            version: '7.X.X'
      - job:  restore 
        steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: '**/**/Shopping.API/*.csproj'
        
        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'Build'
            projects: '**/**/Shopping.API/*.csproj'
  - stage: Builddocker
    jobs:
    - job: 
      steps:
      - task: CmdLine@1
        inputs:
          filename: '$(Build.SourcesDirectory)'
          arguments: 'docker login $(artifactory_url) -U $(artifactoryuser) -p $(artifactorypass)'
           
      - task: Docker@2
        displayName: dockerbuild
        inputs:
         command: build
         tags: sriram1995/$pipelinename:$buildId
         Dockerfile: '**/**/Shopping.API/**/dockerfile'
      
      - task: Docker@2
        displayName: push
        inputs:
          command: push
