# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: 
        steps:
        - task: DotNetCoreInstaller@1
          displayName: install .net 
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
      - job:  restore 
        steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: '**/**/Shopping.API/*.csproj'
        
        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: '**/**/Shopping.API/*.csproj'
  - stage: Builddocker
    jobs:
    - job: 
      steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
#      - task: CmdLine@2
 #       inputs:
  #        script: 'docker login $(artifactory_url) -u $(artifactoryuser) -p $(artifactorypass)'
        
      - task: Docker@1
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'dockerhub'
          command: 'login'
      
           
      - task: Docker@2
        displayName: dockerbuild
        inputs:
          containerRegistry: 'dockerhub'
          repository: 'sriram1995'
          command: 'build'
          Dockerfile: '**/Shopping/Shopping.API/Dockerfile'
          
      
      - task: Docker@2
        inputs:
            containerRegistry: 'dockerhub'
            repository: 'sriram1995'
            command: 'push'
            tags: '$(Build.BuildId)'